[build]
  # 你 VuePress 最终生成的目录
  publish = "docs/.vuepress/dist"
  # 构建命令
  command = "npm run build"

[build.environment]
  # 使用稳定版 Node，避免 Node 22 的兼容问题
  NODE_VERSION = "20.12.2"

  # 有些 VuePress 插件 / webpack 配置会读取 NODE_OPTIONS
  # 限制内存使用，防止 OOM，可以设置为 3~4GB 左右
  NODE_OPTIONS = "--max_old_space_size=3072"

  # 如果你在 vue.config.js / webpack.config.js 里读取这个 env 变量，可以关闭 sourcemap
  GENERATE_SOURCEMAP = "false"

  # 可选，部分插件如果支持生产模式优化
  NODE_ENV = "production"

[context.production]
  # Netlify build 超时时间（默认15分钟，这里加长一点）
  command_timeout = 1800

# 如果你用 preview deploy，可以单独配 context
#[context.deploy-preview.environment]
#  NODE_VERSION = "20.12.2"
#  NODE_OPTIONS = "--max_old_space_size=3072"
#  GENERATE_SOURCEMAP = "false"
